### ISSUE TITLE
Unable to execute shell on Linux

### ISSUE THREAD

**Issue by Kendubu1** [Azure/azure-websites-java-remote-debugging#1]
Kept failing when calling the debug session class.

Example script used on linux
#!/bin/sh
java -cp ..\lib\commons-cli-1.2.jar:..\lib\commons-codec-1.9.jar:..\lib\javax-websocket-client-impl-9.1.0.v20131115.jar:..\lib\javax-websocket-server-impl-9.1.0.v20131115.jar:..\lib\javax.websocket-api-1.0.jar:..\lib\jetty-io-9.1.0.v20131115.jar:..\lib\jetty-util-9.1.0.v20131115.jar:..\lib\slf4j-api-1.7.6.jar:..\lib\slf4j-jdk14-1.7.6.jar:..\lib\slf4j-log4j12-1.7.6.jar:..\lib\websocket-api-9.1.0.v20131115.jar:..\lib\websocket-client-9.1.0.v20131115.jar:..\lib\websocket-common-9.1.0.v20131115.jar:..\lib\websocket-server-9.1.0.v20131115.jar:..\lib\websocket-servlet-9.1.0.v20131115.jar:..\lib\commons-logging-1.1.3.jar:. org.azure.waws.DebugSessionMain

Also recieved the follow errors
Failed to connect to remote VM
com.sun.jdi.connect.spi.ClosedConnectionException

**Comment by wilgert** [comment]
I am experiencing the same issue.

**Comment by jvano** [comment]
For Linux you will need to try using SSH tunneling:
https://azure.github.io/AppService/2018/05/07/New-SSH-Experience-and-Remote-Debugging-for-Linux-Web-Apps.html
